# Generated by Django 2.2.4 on 2019-09-04 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='cteated_time',
            new_name='created_time',
        ),
    ]
